### PR TITLE
fixed use fake_useragent status 403

### PR DESCRIPTION
**Pull request by bestK**
use fake_useragent  fix 
https://github.com/SauravKanchan/10minutemail/issues/2

### CODE REVIEW

**Comment by knez** [comment]
Your commit solves the issue for me. I had to change "user-agent" to "User-Agent". Otherwise I get 403

**Review by TaquitoSlayer — APPROVED** [review]

**Comment by TaquitoSlayer** [comment]
This doesn't fix this anymore. You need a proper TLS for cloudflare.

**Comment by 1997cui** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
SeanCravener, @keyding, @pneugebala, @fly51fly, @GGAlanSmithee, @lixuejiang, @anthonygraignic, @DickiesMagicShow, @CastilloLuis, @kevinleonsmith, @qftgtr, @itenl, @sdcrypt0, @DeRain, @DDecoene, @stonegao, @JulyMoon87, @lidd77, @azimuth3d, @seanbhart

**Review by JulyMoon87 — APPROVED** [review]

**Review by JulyMoon87 — APPROVED** [review]

**Review by JulyMoon87 — COMMENTED** [review]
src/minutemail.py

**Review by SauravKanchan — APPROVED** [review]

**Pull request merged**
